sudo: required

services:
  - docker

before_install:
  - docker build -t rafal712/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rafal712/react-test npm test -- --coverage

after_success:
  - docker build -t rafal712/multi-client ./client
  - docker build -t rafal712/multi-nginx ./nginx
  - docker build -t rafal712/multi-server ./server
  - docker build -t rafal712/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rafal712/multi-client
  - docker push rafal712/multi-ngin
  - docker push rafal712/multi-server
  - docker push rafal712/multi-worker