sudo: required

services:
  - docker

before_install:
  - docker build -t rafal712/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rafal712/react-test npm test

after_success:
  - docker build -t rafal712/multi-client ./client
  - docker build -t rafal712/multi-nginx ./nginx
  - docker build -t rafal712/multi-server ./server
  - docker build -t rafal712/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rafal712/multi-client
  - docker push rafal712/multi-nginx
  - docker push rafal712/multi-server
  - docker push rafal712/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Multi-Docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-598654767674"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY